language: ruby
cache: bundler
sudo: false
dist: precise
rvm:
  - 2.2
  - 2.4
gemfile:
  - spec/travis/gemfiles/Gemfile-5
  - travis/gemfiles/Gemfile-5_1
env:
  matrix:
    - DB=mysql2
#    - DB=postgresql
    - DB=sqlite3
before_script:
  - bundle update
  - cp travis/database.travis.yml spec/dummy/config/database.yml
  - mysql -e 'create database travis_ci_test'
  - psql -c 'create database travis_ci_test' -U postgres
  - bundle exec rake db:migrate
script:
  - bundle exec rspec